stages:
  - build
  - deploy

build_stage:
  image: node:alpine
  stage: build
  only:
    - main
  script:
    - npm install --prefix frontend
    - CI=false npm run build --prefix frontend
  artifacts:
    paths:
      - frontend/build/
    expire_in: 1 hour

deploy_stage:
  image: python:latest
  stage: deploy
  only:
    - main
  script:
    - pip install awscli
    - aws s3api create-bucket --bucket $S3_BUCKET
    - aws s3api put-public-access-block --bucket $S3_BUCKET --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"
    - |
      aws s3api put-bucket-policy --bucket $S3_BUCKET --policy "{ \"Version\": \"2012-10-17\", \"Statement\": [ { \"Sid\": \"PublicReadGetObject\", \"Effect\": \"Allow\", \"Principal\": \"*\", \"Action\": \"s3:GetObject\", \"Resource\": \"arn:aws:s3:::$S3_BUCKET/*\" }] }"
    - aws s3 website s3://$S3_BUCKET --index-document index.html --error-document index.html
    - aws s3 sync ./frontend/build s3://$S3_BUCKET
